### ISSUE TITLE
Bonus screens

### ISSUE THREAD

**Issue by joshpitzalis** [Prolifiko/prolifiko#114]
Screen 2 – Show your skills. Is it possible to have bold text as per original? Make ‘instructional’ and ‘review post’ bold.

Screen 3. Make ‘informational’ and ‘prediction’ bold.

Screen 4. Make ‘argument or debate’ and ‘inspirational’ bold.

Screen 5. Make ‘personal journey’ and commentary’ bold.

Missing text with changed word: Click the star to complete the bonus.

Couldn’t make this star go gold – not changed on my progress either.

Screen 6. There’s a small square on the screen between heading and text.

Text needs writing as there are no reminders - delete third sentence.

**Comment by anniva** [comment]
These are now fixed in the content.json -> I'll gitter the new one.. So after @rjmk you do the mongo update please close this issue
